# Generated by Django 4.1.13 on 2024-05-04 10:36

import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('math_marks_hs', models.IntegerField()),
                ('science_marks_hs', models.IntegerField()),
                ('english_marks_hs', models.IntegerField()),
                ('hindi_marks_hs', models.IntegerField()),
                ('hs_percentage', models.FloatField(blank=True, null=True)),
                ('physics_marks_10p2', models.IntegerField()),
                ('chemistry_marks_10p2', models.IntegerField()),
                ('mathematics_marks_10p2', models.IntegerField()),
                ('marks_10p2_percentage', models.FloatField(blank=True, null=True)),
                ('preference_1', models.CharField(blank=True, choices=[('computer_science_engineering', 'Computer Science and Engineering'), ('electronics_communication_engineering', 'Electronics and Communication Engineering'), ('information_technology', 'Information Technology')], max_length=50, null=True)),
                ('preference_2', models.CharField(blank=True, choices=[('computer_science_engineering', 'Computer Science and Engineering'), ('electronics_communication_engineering', 'Electronics and Communication Engineering'), ('information_technology', 'Information Technology')], max_length=50, null=True)),
                ('preference_3', models.CharField(blank=True, choices=[('computer_science_engineering', 'Computer Science and Engineering'), ('electronics_communication_engineering', 'Electronics and Communication Engineering'), ('information_technology', 'Information Technology')], max_length=50, null=True)),
                ('branch', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('mobilenumber', models.CharField(max_length=15)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
